# Generated by Django 3.2.2 on 2021-05-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='page'),
        ),
    ]
